language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly

script:
  - julia --check-bounds=yes --inline=no -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Chemfiles"); Pkg.test("Chemfiles"; coverage=true)'
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_JULIA_VERSION}" == "1.0" ]]; then
        julia -e 'cd(Pkg.dir("Chemfiles")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
        ./scripts/build-docs.sh
        cd ${TRAVIS_BUILD_DIR}
    fi
  - cd ${TRAVIS_BUILD_DIR}
  - ./scripts/check_used_functions.py
  - ./scripts/check_docs.py

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        branch: master
        condition: "${TRAVIS_OS_NAME} == linux && ${TRAVIS_JULIA_VERSION} == 1.0"
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        tags: true
        condition: "${TRAVIS_OS_NAME} == linux && ${TRAVIS_JULIA_VERSION} == 1.0"
