language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
install:
  - git fetch --unshallow
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Chemfiles")'
script:
  - julia --check-bounds=yes --inline=no -e 'Pkg.test("Chemfiles"; coverage=true)'
after_success:
  - |
    if test "$TRAVIS_JULIA_VERSION" == "release"; then
        julia -e 'cd(Pkg.dir("Chemfiles")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    fi
