language: julia
julia:
  - nightly
install:
  - git fetch --unshallow
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Chemharp")'
script:
  - julia --check-bounds=yes --inline=no -e 'Pkg.test("Chemharp"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Chemharp")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
