environment:
  matrix:
  - JULIAVERSION: "julialang/bin/winnt/x86/0.4/julia-0.4.0-win32.exe"
  - JULIAVERSION: "julialang/bin/winnt/x64/0.4/julia-0.4.0-win64.exe"
  - JULIAVERSION: "julianightlies/bin/winnt/x86/julia-latest-win32.exe"
  - JULIAVERSION: "julianightlies/bin/winnt/x64/julia-latest-win64.exe"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  - ps: (new-object net.webclient).DownloadFile(
              $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
              "C:\projects\julia-installer.exe"
        )
  - C:\projects\julia-installer.exe /S /D=C:\projects\julia

build_script:
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.clone(pwd(), \"Chemfiles\"); Pkg.build(\"Chemfiles\")"

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"Chemfiles\")"
